apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name}}
  labels:
    name: {{ .Values.frontend.label}}
  annotations:
{{include "application-frontend.annotation" . | indent 4}}
spec:
  replicas: {{ .Values.frontend.replicas}}
  selector:
    matchLabels:
{{include "application-frontend.labels" . | indent 6}}
  template:
    metadata:
      labels:
{{include "application-frontend.labels" . | indent 8}}
    spec:
      containers:
      - name: {{ .Values.frontend.name}}
        image: {{ .Values.frontend.image}}
        ports:
        - containerPort: {{ .Values.frontend.port}}
          name: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name}}
  labels:
    name: {{ .Values.frontend.service.label}}
spec:
  type: {{ .Values.frontend.service.type}}
  selector:
{{include "application-frontend.labels" . | indent 4}}
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.service.port}}
    targetPort: {{ .Values.frontend.service.port}}
    nodePort: {{ .Values.frontend.service.nodePort}}