apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    name: frontend-dep-label
  annotations:
    class: frontend-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
      app: diceK8s-project
  template:
    metadata:
      labels:
        tier: frontend
        app: diceK8s-project
    spec:
      containers:
      - name: frontend
        image: sannan1357/frontend:v1.0
        ports:
        - containerPort: 8080
          name: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend-svc
spec:
  type: NodePort
  selector:
      tier: frontend
      app: diceK8s-project
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31500
    